### ISSUE TITLE
Where have all the sources gone..?

### ISSUE THREAD

**Issue by Rijom** [boost-ext/sml#576]
There used to be a bunch of header files that were merged together using pph.sh to create sml.hpp.
[0ee0815](https://github.com/boost-ext/sml/commit/0ee081597e3d8c79792ce0e04ac0fc42a2380656) got rid of all those files leaving only the generated sml.hpp.

Reading the amalgamated header is significantly more difficult. I am seriously worried about maintenance at this point.

Was this change intentional? Am I missing something?

**Comment by sdebionne** [comment]
I am also worried. The commit message reads **SML 2.0: sml.lite + sml.rust**, so what now? SML is a rust library? The version was tagged v1.1.8 so what about the 2.0 in the commit?

**Comment by pschiager** [comment]
@krzysztof-jusiak Any info on this for new readers?

**Comment by krzysztof-jusiak** [comment]
The change to use a single header was indeed intentional. Most contributions were only updating sml.hpp making it really hard to keep up to date with other files. By only having a single point of true is much easier to be consistent, deploy and contribute. No magic with additional build scripts too. The change didn't affect neither examples nor tests. It's purely for long term maintainability. I understand that going through a single file instead of multiple files is a love/hate relationship but it allows to avoid a lot of confusion and IMHO it's better for the project.

And yeah, SML is NOT and NEVER will be a rust library (there is a small prototype available for rust but nothing more and it's not part of SML repo anymore). C++ version is by far superior and it will stay like that.
